#include <stdio.h>

int iscaps(int ch);

int main()
{
	int c;

	do
	{
		c = getchar();
		if(iscaps(c)) // uses uppercase letters generated by iscaps functions
            putchar(c); // and displays only uppercase from above
	}
	while( c != '\n');

	return(0);
}

int iscaps(int ch)
{
	if( ch < 'A' || ch > 'Z') // confirms if input is uppercase
		return(0);
	else
		return(1);
}

